language: ruby
rvm:
 - "2.2.2"
env:
 - DB=postgres

before_script:  
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS travis_ci_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database travis_ci_test;' -U postgres; fi"
  - cp config/database.yml.travis config/database.yml
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
