menubar: false
toolbar:
  - undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist | link unlink image | removeformat
plugins:
  - table
  - image
  - link
